sudo: false

language: erlang

before_install:
  - pip install --user cpp-coveralls coveralls-merge

install:
  - ./configure --enable-gcov
  - rebar get-deps
  - gcc -v
  - rebar compile -vvv

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json

otp_release:
  - 17.1
  - 17.5
  - 18.0
